# Generated by Django 5.1.15 on 2026-06-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('vehicles', 'Vehicles'), ('furniture', 'Furniture'), ('sports', 'Sports'), ('clothing', 'Clothing'), ('books', 'Books'), ('home', 'Home'), ('services', 'Services'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
